# general
shell = "pwsh"

[window]
decorations = "Full"
opacity = 0.9
dimensions = { columns = 130, lines = 30 }
position = { x = 100, y = 100 }
padding = { x = 2, y = 2 }

[font]
normal = { family = "UDEV Gothic NF", style = "Regular" }
size = 13.0

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "UnderLine" }