# https://docs.helix-editor.com/editor.html

theme = "dark_plus"

[editor]
line-number = "realtive"
true-color = "true"
rulers = [80]
color-modes = "true"
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = ["diganostics", "selections", "position", "file-encoding", "file-line-encoding", "file-type"]
separator = "|"

[editor.lsp]
display-messagees = "true"
display-inlay-hints = "true"
snippets = "true"


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
